/**
 * Reading a field's declared type out of the app's json schema, for a path the comparison found.
 *
 * Altinn serves the model's schema at `{app}/api/jsonschema/{dataType}`, generated by Studio from
 * the same XSD the C# model came from. Its shape: no `properties` at the root, a `@xsdRootElement`
 * naming the xml root, a `oneOf` pointing into `$defs`, and the XSD's own type kept alongside the
 * json one as `@xsdType`. That annotation is the useful half, because json schema calls a date a
 * string and the XSD does not.
 *
 * Nothing here guesses. A path that does not resolve exactly gets no type, because a wrong type
 * on a difference is worse than none: an unresolved path usually means the model has no such
 * field, which is why it was dropped in the first place.
 */

type Schema = Record<string, unknown>;

function asSchema(value: unknown): Schema | null {
    return value && typeof value === "object" && !Array.isArray(value) ? (value as Schema) : null;
}

function asString(node: Schema, key: string): string | null {
    return typeof node[key] === "string" ? (node[key] as string) : null;
}

/** Follows `$ref` into the document, and through a single-branch `oneOf`, `anyOf` or `allOf`. */
function deref(node: Schema | null, root: Schema, depth = 0): Schema | null {
    if (!node || depth > 20) return null;

    const ref = asString(node, "$ref");
    if (ref) {
        // Only local pointers, which is all Studio emits: #/$defs/Name.
        if (!ref.startsWith("#/")) return null;
        let target: unknown = root;
        for (const step of ref.slice(2).split("/")) {
            const here = asSchema(target);
            if (!here) return null;
            target = here[decodeURIComponent(step.replace(/~1/g, "/").replace(/~0/g, "~"))];
        }
        return deref(asSchema(target), root, depth + 1);
    }

    for (const key of ["oneOf", "anyOf", "allOf"]) {
        const branches = node[key];
        if (!Array.isArray(branches)) continue;
        // More than one branch means the schema offers a choice, and picking one would be a
        // guess. A single branch is the wrapper Studio emits at the root.
        if (branches.length !== 1) return null;
        return deref(asSchema(branches[0]), root, depth + 1);
    }

    return node;
}

/** A repeating group is an array in the schema, so its rows live one level down in `items`. */
function intoItems(node: Schema | null, root: Schema): Schema | null {
    if (!node) return null;
    const items = asSchema(node["items"]);
    return items ? deref(items, root) : node;
}

interface Segment {
    name: string;
    attribute: boolean;
}

/** "/ettrinn/part[2]/@altinnRowId" as its parts, with indexes dropped: they pick a row, not a field. */
function segments(path: string): Segment[] {
    return path
        .split("/")
        .filter(Boolean)
        .map((raw) => {
            const withoutIndex = raw.replace(/\[\d+\]$/, "");
            return withoutIndex.startsWith("@") ? { name: withoutIndex.slice(1), attribute: true } : { name: withoutIndex, attribute: false };
        });
}

/** A property by name, allowing for an attribute that the schema may or may not prefix with @. */
function property(node: Schema | null, segment: Segment, root: Schema): Schema | null {
    const properties = asSchema(node?.["properties"]);
    if (!properties) return null;
    const candidates = segment.attribute ? [`@${segment.name}`, segment.name] : [segment.name];
    for (const candidate of candidates) {
        const found = asSchema(properties[candidate]);
        if (found) return deref(found, root);
    }
    return null;
}

/**
 * The type to show for a field: the XSD type where the schema kept it, otherwise the json schema
 * format, otherwise its plain type. An enumeration says so, since that is often why a value was
 * rejected or rewritten.
 */
function describeType(node: Schema): string | null {
    const xsd = asString(node, "@xsdType");
    const format = asString(node, "format");
    const type = asString(node, "type");
    const base = xsd ?? format ?? type;
    if (!base) return null;
    return Array.isArray(node["enum"]) ? `${base}, one of ${(node["enum"] as unknown[]).length}` : base;
}

/**
 * Resolves each path against the schema, returning only the ones it could place.
 *
 * The first segment is the xml root element, which is the schema's root object rather than one of
 * its properties, so it is consumed against `@xsdRootElement` before the walk begins.
 */
export function resolveFieldTypes(schema: unknown, paths: string[]): Record<string, string> {
    const root = asSchema(schema);
    if (!root) return {};
    const rootElement = asString(root, "@xsdRootElement");
    const rootNode = deref(root, root);
    if (!rootNode) return {};

    const types: Record<string, string> = {};
    for (const path of paths) {
        const parts = segments(path);
        const first = parts[0];
        if (!first) continue;

        // The root element names the document, not a field in it. Where the schema does hold it
        // as a property, that is followed instead.
        let node: Schema | null = rootNode;
        let rest = parts;
        if (!rootElement || first.name === rootElement) {
            rest = parts.slice(1);
        } else if (property(rootNode, first, root)) {
            node = property(rootNode, first, root);
            rest = parts.slice(1);
        }

        for (const segment of rest) {
            node = property(intoItems(node, root), segment, root);
            if (!node) break;
        }

        // The root itself has no type worth showing, only its fields do.
        if (!node || rest.length === 0) continue;
        const described = describeType(node);
        if (described) types[path] = described;
    }
    return types;
}
